In [1]:
import numpy as np

In [11]:
array = np.random.randint(1, 21, size=(5,5))
array

array[:,2]= 1
array

array([[10,  5,  1,  2, 15],
       [ 2,  6,  1,  7,  6],
       [11,  8,  1,  4, 14],
       [ 2, 11,  1, 14, 19],
       [ 6, 13,  1, 18,  5]], dtype=int32)

In [12]:
array = np.arange(1,17).reshape(4,4)
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [16]:
np.fill_diagonal(array, 0)
array

array([[ 0,  2,  3,  4],
       [ 5,  0,  7,  8],
       [ 9, 10,  0, 12],
       [13, 14, 15,  0]])

In [19]:
array = np.arange(1,37).reshape(6,6)
print(array)
subarray = array[2:5, 1:4]
subarray

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


array([[14, 15, 16],
       [20, 21, 22],
       [26, 27, 28]])

In [24]:
array = np.random.randint(1,10,size=(5,5) )
print(array)
borders = np.concatenate( (array[0, :] , array[1 : , 4], array[4, :-1], array[1:-1, 0]) )
borders

[[4 5 2 5 1]
 [7 9 5 2 5]
 [6 4 1 2 5]
 [6 5 4 9 7]
 [2 9 1 3 2]]


array([4, 5, 2, 5, 1, 5, 5, 7, 2, 2, 9, 1, 3, 7, 6, 6], dtype=int32)

In [7]:
array1 = np.random.randint(1,13, size=(3,4))
array2 = np.random.randint(1, 13, size=(3,4))
print(array1)
print(array2)

print(array1 - array2)
print(array1 + array2)
print(array1 * array2)
print(array1 / array2)

[[ 6  7  3  2]
 [10  9  9  8]
 [11 11 10  1]]
[[ 4  1  6 10]
 [ 6  8 10 12]
 [ 7  7  1 11]]
[[  2   6  -3  -8]
 [  4   1  -1  -4]
 [  4   4   9 -10]]
[[10  8  9 12]
 [16 17 19 20]
 [18 18 11 12]]
[[24  7 18 20]
 [60 72 90 96]
 [77 77 10 11]]
[[ 1.5         7.          0.5         0.2       ]
 [ 1.66666667  1.125       0.9         0.66666667]
 [ 1.57142857  1.57142857 10.          0.09090909]]


In [ ]:
array = np.arange(1, 17).reshape(4,4)
print(array)

print(np.sum(array, axis=0))  # columns sum
print(np.sum(array, axis=1))   # rows sum


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[28 32 36 40]
[10 26 42 58]


In [11]:
array = np.random.randint(1,26, size=(5,5))
print(np.mean(array))
print(np.median(array))
print(np.std(array))
print(np.var(array))

13.72
17.0
8.01758068247523
64.2816


In [16]:
array = np.arange(1, 10).reshape(3,3)
mean = np.mean(array)
std = np.std(array)

normalized = (array - mean) /std
print(normalized)
print(np.mean(normalized))
print(np.std(normalized))

[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]
0.0
1.0


In [4]:
array1 =  np.random.randint(1, 10, size=(3,3)) 
array2 = np.array([1] *3).reshape(3,)
print(array1)
print(array2)
print(array1 + array2)

[[8 2 4]
 [3 3 6]
 [6 7 5]]
[1 1 1]
[[9 3 5]
 [4 4 7]
 [7 8 6]]


In [ ]:
array = np.random.randint(1,17, size=(4,4))
print(array)
arr2 = np.array([1 , 2, 3, 4]).reshape(4, )
print(arr2[: , np.newaxis])
result = array - arr2[:, np.newaxis]  # convert it to a new axis
print(result)

[[14  4  4  5]
 [ 4 15  7 13]
 [ 7 14 12  5]
 [ 9 13  8  5]]
[[1]
 [2]
 [3]
 [4]]
[[13  3  3  4]
 [ 2 13  5 11]
 [ 4 11  9  2]
 [ 5  9  4  1]]


In [ ]:
mat = np.random.randint(1, 10, size=(3,3))
print(mat)

# determinant
det = np.linalg.det(mat)
print(det)

# inverse
inv = np.linalg.inv(mat)
print(inv)

# eigen value
eigen = np.linalg.eigvals(mat)
print(eigen)

[[5 2 8]
 [8 4 9]
 [7 8 6]]
78.0
[[-0.61538462  0.66666667 -0.17948718]
 [ 0.19230769 -0.33333333  0.24358974]
 [ 0.46153846 -0.33333333  0.05128205]]
[18.91810121+0.j         -1.95905061+0.53400006j -1.95905061-0.53400006j]


In [31]:
arr1 = np.arange(1,7).reshape(2,3)
arr2 = np.arange(1, 7).reshape(3,2)
print(arr1)
print(arr2)

res = np.linalg.matmul(arr1, arr2)
print(res)
print(np.dot(arr1, arr2))
print(np.matmul(arr1, arr2))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[22 28]
 [49 64]]
[[22 28]
 [49 64]]
[[22 28]
 [49 64]]


In [24]:
array = np.arange(1, 10).reshape(3,3)
print(array)

array = array.reshape(1, 9)
print(array)

array = array.reshape(9,1)
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [37]:
arr = np.random.randint(1, 26, size=(5,5))
print(arr)

arr = arr.flatten()
print(arr)

arr = arr.reshape(5,5)
print(arr)

[[15 11  1 23  6]
 [12 17  9  5 11]
 [19 23 19 15 15]
 [20 13 19 21 24]
 [25 23  1 15  8]]
[15 11  1 23  6 12 17  9  5 11 19 23 19 15 15 20 13 19 21 24 25 23  1 15
  8]
[[15 11  1 23  6]
 [12 17  9  5 11]
 [19 23 19 15 15]
 [20 13 19 21 24]
 [25 23  1 15  8]]


In [40]:
arr = np.random.randint(1, 26, size=(5,5))
print(arr)
corner_elements = arr[[0 , 0, -1, -1 ], [0, -1, 0, -1]]
print(corner_elements)

[[21 16 23 17 17]
 [25 17 22  4 14]
 [ 4  9  3 20 23]
 [ 7 11 17  3 17]
 [ 5 15 14  6  4]]
[21 17  5  4]


In [43]:
arr = np.random.randint(1, 17, size=(4,4))
print(arr)

arr[arr > 10] = 10

print(arr)

[[12  4 12 12]
 [14 11  3 13]
 [ 1 16 13  8]
 [ 8 12  5  3]]
[[10  4 10 10]
 [10 10  3 10]
 [ 1 10 10  8]
 [ 8 10  5  3]]


In [ ]:
data_type = [('name', 'U20'), ('age', np.int64), ('weight', np.double) ]
data = [('Hardik Gaur', 21, 72.0), ('Thomas Shelby',38, 70 ), ('Eren Yeager', 12, 58)]

arr = np.array(data, dtype=data_type)
print(arr)

arr = np.sort(arr, order='age')   
print(arr)

[('Hardik Gaur', 21, 72.) ('Thomas Shelby', 38, 70.)
 ('Eren Yeager', 12, 58.)]
[('Eren Yeager', 12, 58.) ('Hardik Gaur', 21, 72.)
 ('Thomas Shelby', 38, 70.)]


In [56]:
data_type = [('x' , np.int64), ('y', np.int64)]
data = [(1, 8), (3, 15), (89, 343)]
arr = np.array(data, dtype=data_type)
print(arr)

euclidean_distances = np.sqrt( (arr['x'][:, np.newaxis] - arr['x'] ) ** 2 + (arr['y'][:, np.newaxis] - arr['y']) ** 2 )
print(euclidean_distances)





[( 1,   8) ( 3,  15) (89, 343)]
[[  0.           7.28010989 346.36541398]
 [  7.28010989   0.         339.08700948]
 [346.36541398 339.08700948   0.        ]]


In [ ]:
import numpy.ma as ma

arr = np.random.randint(1, 17, size=(4,4))
print(arr)
arr = ma.masked_greater(arr, 10)
print(arr)
sum = np.sum(arr)
print(sum)


[[ 7 16  7  7]
 [ 1  4  6  2]
 [14  5  8 13]
 [ 7  1  7 15]]
[[7 -- 7 7]
 [1 4 6 2]
 [-- 5 8 --]
 [7 1 7 --]]
62


In [65]:
arr = np.random.randint(1,10,size=(3,3))
print(arr)

arr = ma.masked_array(arr, mask=np.eye(3, dtype=np.int64))
print(arr)

mean = np.mean(arr)
print(mean)

arr = arr.filled(mean)

print(arr)

[[2 8 9]
 [6 8 4]
 [8 5 6]]
[[-- 8 9]
 [6 -- 4]
 [8 5 --]]
6.666666666666667
[[6 8 9]
 [6 6 4]
 [8 5 6]]
