In [1]:
1 + 1

2

In [2]:
import numpy as np

In [9]:
arr = np.array([1,2,3,4,5])

print(arr)
print(type(arr))
print(arr.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [15]:
arr2= np.array([1,2,3,4,5])
arr2.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [16]:
arr3 = np.array([[1,2,3,4,5]])
arr3.shape

(1, 5)

In [24]:
arr4 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
arr4.shape

(2, 5)

In [ ]:
arr4.reshape(3,4) # give an error as 3*4 > 10

ValueError: cannot reshape array of size 10 into shape (3,4)

In [26]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [29]:
np.ones((3,4), dtype=np.int32)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [30]:
np.zeros((3,4), dtype=np.int32)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

In [31]:
## identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
arr = np.array([ [1,2,3], [4,5,6] ])

print(arr)
print("Shape : " , arr.shape)
print('Dimensions : ' , arr.ndim)
print('Size (number of elements) : ', arr.size)
print("Data type : ", arr.dtype) 
print("Item size (in bytes) : ", arr.itemsize)

[[1 2 3]
 [4 5 6]]
Shape :  (2, 3)
Dimensions :  2
Size (number of elements) :  6
Data type :  int64
Item size (in bytes) :  8


In [39]:
# Numpy Vectorized operations

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

# element wise addition
print('Addition : ', arr1  + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

Addition :  [11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]


In [44]:
# universal function -> functions that are applied to the whole array
arr = np.array([2,3,4,5,6])

# square root
print(np.sqrt(arr))

# Exponential
print(np.exp(arr))

# Sine
print(np.sin(arr))


[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]


In [45]:
## slicing and indexing

arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [53]:
print(arr[0][0])
print(arr[0:2])

1
[[1 2 3 4]
 [5 6 7 8]]


In [51]:
arr[1:, 2:]

array([[ 7,  8],
       [11, 12]])

In [54]:
arr[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [55]:
# Modify array elements

arr[0,0] = 200
print(arr)

[[200   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [56]:
arr[1:] = 100
arr

array([[200,   2,   3,   4],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [61]:
# statistical concepts -- Normalization
## to have a mean of 0 and standard deviation of 1

data = np.array([1,2,3,4,5])

# calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# normalize the data
normalized_data = (data -  mean) / std_dev
print("Normalized data : " , normalized_data)


Normalized data :  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [63]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

# mean
mean = np.mean(data)
print(mean)

# median
median = np.median(data)
print(median)

# standard deviation
std_dev = np.std(data)
print(std_dev)

# variance 
variance = np.var(data)
print(variance)

5.5
5.5
2.8722813232690143
8.25


In [64]:
# logical operation

data = np.array([1,2,3,4,5,6])

data > 3

array([False, False, False,  True,  True,  True])

In [66]:
data[data > 3]

array([4, 5, 6])

In [68]:
data[(data > 1) & (data <6) ]  # use bitwise &

array([2, 3, 4, 5])